name: CI

on:
    pull_request:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    validation:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                        '8.1',
                        '8.2',
                        '8.3',
                ]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@2.27.0
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl, pdo_mysql

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Composer cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --prefer-dist --no-interaction --optimize-autoloader

            - name: Check PHP for syntax errors
              run: find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

            - name: PHPStan checks
              run: composer stan

            - name: CodeStyle checks
              run: composer cs-check

    tests:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                        '8.1',
                        '8.2',
                        '8.3',
                ]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@2.27.0
              with:
                php-version: ${{ matrix.php-version }}
                extensions: mbstring, intl, pdo_mysql

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Composer cache
              uses: actions/cache@v3
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --prefer-dist --no-interaction --optimize-autoloader

            - name: Run tests
              run: |
                  composer test

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
